### PR TITLE
Added live search to AssetSearch component

### PR DESCRIPTION
**Pull request by mrtraser**
- redo documentation for AssetSearch component
- added tests

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-112.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
What is the liveSearchResults prop for?

**Comment by mrtraser** [comment]
@f1cognite we need it to pass search results to AssetSearch component to display in live search.

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-112.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-112.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
@mrtraser I don't see "AssetSearch" in the Storybook but I see "Search" component there. Shouldn't we hide Search if this is just an internal component?

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-112.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-112.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-112.gearboxjs.preview.cogniteapp.com

**Pull request merged**
