### PR TITLE
fix: componentWillUpdate is deprecated

### PR DESCRIPTION
**Pull request by stonecrafter**
The warning is bugging me when I'm using the component :)

Also checked there are no more componentWillUpdate elsewhere in the codebase

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-593.gearboxjs.preview.cogniteapp.com

**Comment by stonecrafter** [comment]
I don't know who is the right person to ask for reviews actually, but someone please review this :)

**Comment by nalaka** [comment]
Thanks @stonecrafter for catching this, and the PR - we'll review and get this into the next release.

**Comment by polomani** [comment]
@mrtraser please, check if commit messages make sense.
this one screwed our changelog a bit

**Pull request merged**
