### PR TITLE
[WIP] feat: new svg viewer implementation

### PR DESCRIPTION
**Pull request by ghost**
THIS IS STILL WIP, DO NOT MERGE!

I wanted to try and play around in finding a good alternative to our current P&ID viewer that can offer a better interface and experience, allowing for smoother zooming and navigation.

It is highly WIP currently, the features that needs to be done are:

- [x] view svg
- [x] onclick
- [x] zoom, scroll, pinch, touch
- [x] highlight effectively
- [ ] highlight on search
- [ ] zoom properly when file has transform
- [ ] tests

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-627.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
could you give some explanation in here? is it finished?

**Comment by dlcognite** [comment]
Nono, not at all yet, I wanted to play wtih a new viewer and see if there's improvements to usage. It has better zoom handling and general navigation atm. However, it is still missing the ability to highlight on search properly.

**Comment by polomani** [comment]
@dlcognite no?(

**Comment by dlcognite** [comment]
Hehe there will be a png based interactive p&id viewer soon, based on
https://dlcognite.github.io/react-picture-annotation/?path=/story/annotator--no-edit

**Pull request closed without merging**
