### PR TITLE
Enabled keyboard navigation by default

### PR DESCRIPTION
**Pull request by anderscognite**

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-233.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-233.gearboxjs.preview.cogniteapp.com

**Comment by mrtraser** [comment]
Why do you need `enableKeyboardNavigation = true` by default? It's more feature then expected behaviour. If you need this just provide `true` value to props.

**Comment by anderscognite** [comment]
I think it is expected default behaviour? Might be wrong here!

**Comment by mrtraser** [comment]
No, it isn't, cause for example in [3d-localizator](https://cognitedata.github.io/javascript-getting-started/3d-localizator/) it will catch keypresses when you'll typing in search bar.

**Comment by anderscognite** [comment]
Hmm, I think this is just a way to avoid the problem with text input etc. Could we, in this react component, solve the problem properly with a hidden div with focus that controls whether or not keyboard is enabled or not?

**Comment by mrtraser** [comment]
Didn't get a point of hidden div element. Could you provide any additional info/example?

**Comment by anderscognite** [comment]
Sorry, hehe! The problem you are describing is that even if a text field has focus, the keyboard events are being sent to the viewer and you will see the camera move as you write asdw etc. This is not what we want.

One solution would be to listen to a focus property on the canvas, and disable the keyboard controls if you lose focus. I haven't found a good way of doing this. Would be awesome if you had any ideas!

I don't think canvas has this, and I seem to remember to have read somewhere that you can add a hidden text field (not general div) that can have this focus property. Not sure though.

**Comment by follan** [comment]
I will look into that solution

**Comment by follan** [comment]
Fixed in #238

**Pull request closed without merging**
