### PR TITLE
AssetScannet input image storybook readme

### LINKED ISSUE #370: Add story description for AssetScanner - Input image usecase

### PR DESCRIPTION
**Pull request by joyrostie**
Adds strorybook readme for AssetScanner's custom image upload.

Closes #370

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-381.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
@joyrostie This PR doesn't close this PR #380. Please update your PR comment

**Comment by joyrostie** [comment]
> @joyrostie This PR doesn't close this PR #380. Please update your PR comment

Miss typed, is closing 370.

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-381.gearboxjs.preview.cogniteapp.com

**Pull request merged**
