### PR TITLE
fix: TimeserisSearch

### PR DESCRIPTION
**Pull request by ArbenPaloja**
TimeserisSearch component doesn't return assetSubtrees with selected asset root, typing on searchbox re…

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-633.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
looks good but there is a problem with commit message
```
$ /home/travis/build/cognitedata/gearbox.js/node_modules/.bin/commitlint-travis
⧗   input: fix: TimeserisSearch with selected asset root, typing on searchbox returns assetSubtrees
✖   header must not be longer than 72 characters, current length is 88 [header-max-length]
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
```

**Comment by ArbenPaloja** [comment]
> looks good but there is a problem with commit message
> 
> ```
> $ /home/travis/build/cognitedata/gearbox.js/node_modules/.bin/commitlint-travis
> ⧗   input: fix: TimeserisSearch with selected asset root, typing on searchbox returns assetSubtrees
> ✖   header must not be longer than 72 characters, current length is 88 [header-max-length]
> ✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
> ```

I didn't get any warnings or errors from myside. Should i recommit it, or it can be fix from you side?

**Comment by polomani** [comment]
your commit message is too long.
set it to something like `fix(timeseries-search): filter on rootAssetIds instead of assetIds `

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-633.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
you need to fix the test as well
```
FAIL src/components/TimeseriesSearch/TimeseriesSearch.test.tsx (21.089s)
  ● TimeseriesSearch › should update assetId with user-selected root asset id
    expect(jest.fn()).toHaveBeenNthCalledWith(expected)
    Expected mock function second call to have been called with:
      {"filter": {"assetIds": [3623339785663936]}, "limit": 100, "search": {"query": "value"}}
    as argument 1, but it was called with
      {"filter": {"rootAssetIds": [3623339785663936]}, "limit": 100, "search": {"query": "value"}}.
```

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-633.gearboxjs.preview.cogniteapp.com

**Review by polomani — APPROVED** [review]
looks good

**Pull request merged**
