### PR TITLE
Deploy Storybook per PR

### LINKED ISSUE #19: Create a pull request storybook link
For every pull request make sure Travis post a comment to the pull request with a link to a storybook for that branch

### PR DESCRIPTION
**Pull request by ghost**
Fixes #19

### CODE REVIEW

**Comment by f1cognite** [comment]
[Storybook](https://pr-33.gearboxjs.preview.cogniteapp.com)

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-33.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-33.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-33.gearboxjs.preview.cogniteapp.com

**Review by mrtraser — APPROVED** [review]
LGTM

**Pull request merged**
