### PR TITLE
docs: storybook landing page

### PR DESCRIPTION
**Pull request by nalaka**
New PR in lieu of outdated #578 

- A collage made from some Gearbox components
- Auto-updating buttons for NPM & Github stats
- High level overview of Gearbox

Screenshot 2020-01-20 at 09 46 48

All component references are in a single **COMPONENTS** section - they automatically order alphabetically.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-603.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-603.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-603.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
This is a draft and it requires some effort to finish. The value is questionable, especially due to the fact that we would like to have this kind of info on docs.cognite.com instead.  
We are currently focusing on other things and therefore can't spend time on it.

**Pull request closed without merging**
