### PR TITLE
docs: update storybook v5.3.8

### PR DESCRIPTION
**Pull request by mrtraser**
**Release notes:**
-

**New components:**
* EventsTimeline (#520, #536, #570)

**Features:**
* Model3DViewer (#480)
* TimeseriesPreview(#554)

**Fixes:**
* TimeseriesChart (#610)

**Docs:**
Storybook has been updated to v5.3.8, added new stories representation in `Docs` tab.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-614.gearboxjs.preview.cogniteapp.com

**Comment by nalaka** [comment]
Notes from review by @nalaka, @amevck. @rumeshwick

1. Timeseries > Annotations - the annotation disappears after switching to other stories and coming back. Everytime the annotation moves to the left and eventually it disappears off the chart. This was noticed during #606 and @amevck has fixed it there.
1. When we click on a story on the sidebar document panel doesn’t scroll to the correct position
1. Some of the titles don’t match - e.g. AssetBreadcrumb > ``Custom breadcrumb rendering` is in sidebar and the docs title is Custom element rendering
1. AssetMeta > Return selected document - no console output observed when a document entry is clicked
1. AssetMeta > Custom Document Priority Categories - the categories used in example are not in the document pane, so user can’t see the effect
1. AssetMeta > Custom Document Category Priority And Sort - the category used in example are not in the document pane, so user can’t see the effect
1. AssetMeta > It is better if the default pane is set to the relevent pant on stories about the non-default pane
1. AssetScanar > Custom ocrRequest - in example code ‘test result’ should be ‘result’
AssetScanar > Custom asset search - maybe we should remove the story (as nothing demonstrable happens) and describe it only in the getAssetsHandlerCustom prop 

We have to review some more components - will make another review comment after that.

**Comment by nalaka** [comment]
Continuing review - @nalaka, @rumeshwick

9. AssetSearch - whatever is entered, the same three results are shown.
1. AssetSearch > Advanced Search - no visible difference without this option. 
1. AssetSearch > Custom Spinner - custom spinner given in example code is not the spinner shown
1. TimeseriesChart - Unnecessary log message 'client.datapoints.retrieve {obj}' on data loader completion. This floods the console when you have the docs panel open as it contains a live update story which reloads every second

Have to review some more components - will make another comment after that.

However, I think most of these observations would have been present even before this PR (with the old storybook)

**Comment by mrtraser** [comment]
`2.` We can do nothing with this cause storybook calculate scroll position right after page rendered, but many of our components have 'fetching' state while they load data before rendering
`9.` Expected behavior
`10.` 
Screenshot 2020-01-24 at 13 24 23
`11.` It's actually shown, you can check with canvas tab to ensure
`12.` It acts as it did before

**Comment by mrtraser** [comment]
`5.` Actually different is obvious
Screenshot 2020-01-24 at 14 42 48

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-614.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-614.gearboxjs.preview.cogniteapp.com

**Comment by mrtraser** [comment]
Really nice catch, @nalaka, I'll fix it.

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-614.gearboxjs.preview.cogniteapp.com

**Pull request merged**
