### PR TITLE
docs(asset-details-panel):  research possibility to use Props  (#533)

### PR DESCRIPTION
**Pull request by amevck**
For showing auto-generated props in new addon-docs MDX, below conditions should be satisfied.

1. imported interfaces/types should be in `.ts` files (not `.tsx` files).
    So we have to move interfaces exported from `.tsx` files to separate `.ts` files.

2. For showing props of higher-order components correctly, we have to create a new fake component that has all the same props as our component and refer that in addon-docs  `Props` component. 

```typescript
export const FakeAssetDetailsPanel: FC<AssetDetailsPanelProps> = () => (
  <></>
);
```
```typescript
<Props of={FakeAssetDetailsPanel} />
```

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-575.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-575.gearboxjs.preview.cogniteapp.com

**Comment by mrtraser** [comment]
Resource, that nice to have a track on:

https://github.com/storybookjs/storybook/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22block%3A+props%22+label%3Abug+is%3Aopen

Regarding HOC:
https://github.com/storybookjs/storybook/issues/8361

Regarding interfaces:
https://github.com/storybookjs/storybook/issues/8482\

The only way to figure out `Props` issue is to refactor codebase by moving interfaces to separate files.

**Comment by mrtraser** [comment]
Closed in favor #588

**Pull request closed without merging**
