### PR TITLE
feat(svg-viewer): use cogs.js buttons on the svg viewer

### PR DESCRIPTION
**Pull request by stonecrafter**
Both OpSup and ADI are switching our applications buttons to use the cogs.js standard rather than antd directly.
The SVGViewer is the only place where the buttons are still, now, inconsistent with the rest of the application.. so it would be nice to update them also.

I believe the original intention was for gearbox to use cogs.js styles where they are available anyway?

Reference:
https://github.com/cognitedata/operational-intelligence/pull/4244
https://github.com/cognitedata/operations-support/pull/3092

Fixes [OPSUP-1039]

[OPSUP-1039]: https://cognitedata.atlassian.net/browse/OPSUP-1039

### CODE REVIEW

**Comment by stonecrafter** [comment]
OHHHH ok right cogs.js isn't open sourced while gearbox is. Never mind! :)

**Comment by dlcognite** [comment]
@stonecrafter its open source now!

**Comment by valgussev** [comment]
Should we open repository as well than (carefully with git history though)? @danlevings

**Comment by danlevings** [comment]
> Should we open repository as well than (carefully with git history though)? @danlevings 

Not yet, git history shows our Figma API keys right now, but we can open it someday, when it becomes a prio 😊

**Comment by polomani** [comment]
@hhenriques has some ideas to make this one work. we'll come back

**Pull request closed without merging**
