### PR TITLE
fix(asset-tree): unreachable nodes appears after changing assetIds prop few times

### PR DESCRIPTION
**Pull request by polomani**
there is a bug on asset tree: 
1. pass some array to assetIds prop
2. click on some nodes to open them up
3. pass `undefined` to assetIds (to render normal tree)
4. pass the same array as it was before
5. -> expanding will not work anymore

I wrote a test for it, but couldn't fix
(also need too fix another test, probably broke it)

### CODE REVIEW

**Comment by polomani** [comment]
@dlcognite you've been working on this property recently, could you have a look?

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-517.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-517.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
@ArbenPaloja you might be interested

**Pull request merged**
