### PR TITLE
fix(time series export): fixes for windows old versions

### PR DESCRIPTION
**Pull request by amevck**

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-528.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-528.gearboxjs.preview.cogniteapp.com

**Comment by mrtraser** [comment]
I would change base here to `release/1.10.0`

**Pull request merged**
