### PR TITLE
styles props for Timeseries pane

### PR DESCRIPTION
**Pull request by joyrostie**
Styles props for Timeseries pane in Asset Meta component 
Storybook readme

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-284.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-284.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-284.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-284.gearboxjs.preview.cogniteapp.com

**Comment by joyrostie** [comment]
Not relevant

**Pull request closed without merging**
