### PR TITLE
chore: add build&test action

### PR DESCRIPTION
**Pull request by polomani**
had to re-encrypt the json file
also added commit lint as an app instead of cmd line tool
(I would prefer cmd, but I did't find)

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-655.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-655.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-655.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-655.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
:tada: :tada: :tada:

**Review by hhenriques — APPROVED** [review]
I have no experience with Github actions but looking at the travis file, it seems ok  ¯\_(ツ)_/¯ @CsabaAlmasi could you please take a look when you have a chance?

Meanwhile, we shouldn't block the security patch. We can iterate on the action if need be

**Review by mrtraser — APPROVED** [review]
great improvement 💪

**Pull request merged**
