### PR TITLE
fix: HOCs typing issue

### PR DESCRIPTION
**Pull request by mrtraser**
Fix types generation for high order components in gearbox.js
Related to https://github.com/cognitedata/gearbox.js/pull/643#issuecomment-619126083

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-646.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-646.gearboxjs.preview.cogniteapp.com

**Review by polomani — APPROVED** [review]
thank you for looking into this

**Comment by mrtraser** [comment]
Fixes https://github.com/cognitedata/gearbox.js/pull/643 [comment](https://github.com/cognitedata/gearbox.js/pull/643#issuecomment-619126083)

**Pull request merged**
