### PR TITLE
#46 new component documenttable

### PR DESCRIPTION
**Pull request by Kamillowl**
added documenttable to Gearbox
added a  story example
fixed lint issues

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-51.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-51.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
@Kamillowl  Anyway we could split this up to multiple lines to make it more readable?

Screenshot 2019-03-27 at 11 17 12

**Comment by Kamillowl** [comment]
> @Kamillowl Anyway we could split this up to multiple lines to make it more readable?
> 
> Screenshot 2019-03-27 at 11 17 12

Could you please provide what "this2 is in words?

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-51.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
I saw you figured it out with the new commit 😄 

Regarding `documentRenderer` could we have an example on how that function should look like?

**Comment by Kamillowl** [comment]
> I saw you figured it out with the new commit 😄
> 
> Regarding `documentRenderer` could we have an example on how that function should look like?

Yes - I tok a guess. fortunately this time I was right :) 
Please also elaborate on example on how that function should look like? Because there is an example of documentrenderer in the storybook already

**Comment by f1cognite** [comment]
Yes, I see the example but it doesn't define the `documentRenderer` function in the example. So from the example I don't know input/output of that function.

**Comment by Kamillowl** [comment]
> Yes, I see the example but it doesn't define the `documentRenderer` function in the example. So from the example I don't know input/output of that function.

That is a good question. This is combined with the general issue we have that typescript proptypes aren't displayed. I think we need to address this rather sooner than later.

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-51.gearboxjs.preview.cogniteapp.com

**Pull request merged**
