### PR TITLE
fix(model 3d viewer): don't mutate boundingBox parameter, fixes #436

### LINKED ISSUE #436: Model3DViewer mutates areaBoundingBox
`Model3DViewer` component mutates `areaBoundingBox` (applies rotation, transformations) passed to it.

Fix:
- It should clone the received `areaBoundingBox` object

Version: `0.4.0`

### PR DESCRIPTION
**Pull request by polomani**
@mrtraser maybe you'll find better idea where to place this one, I didn't manage

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Comment by mrtraser** [comment]
I would move this `clone()` logic to `static getDerivedStateFromProps()`

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-475.gearboxjs.preview.cogniteapp.com

**Pull request merged**
