### PR TITLE
style(asset-scanner): make crop background more transparent

### PR DESCRIPTION
**Pull request by KatyHouse**
Users found it hard to use a scanner with such a dark background.
[OPSUP-369]

[OPSUP-369]: https://cognitedata.atlassian.net/browse/OPSUP-369

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-608.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
@KatyHouse commit message linter failed. text in brackets has to be lowercased (ex. `style(asset-scanner):...`)

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-608.gearboxjs.preview.cogniteapp.com

**Comment by KatyHouse** [comment]
@polomani Thanks

**Comment by mrtraser** [comment]
@KatyHouse, is it acceptable if I change a base to `release/1.12.0` branch and this fix will be published this Friday along with other features?

**Comment by KatyHouse** [comment]
@mrtraser Yes, should be ok, ping me please when it will be published :)

**Comment by KatyHouse** [comment]
@mrtraser Was the release deployed already? :)

**Comment by mrtraser** [comment]
not yet, but it will in 1-2 hours for sure :)

**Pull request merged**
