### PR TITLE
docs: storybook landing page with repo stats

### PR DESCRIPTION
**Pull request by nalaka**
- Buttons for NPM version, download frequency.
- Buttons for Github stars and software license.
- Alphabetical listing of all 21 components
- Temporary logo
- Placeholder docs/ pages for overview, assets, ...

**Note**:  When the stories for `TimeseriesPreview` is converted to the new format, the `docs/about` page should be opened by default.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-578.gearboxjs.preview.cogniteapp.com

**Comment by nalaka** [comment]
Screenshot 2020-01-08 at 10 52 10

**Comment by polomani** [comment]
frankly, I don't see the need of having so many pages. landing one - maybe, but it copies some info from npm anyway. Also there are a lot of WIP, so it's rather a draft. + the data in the table is static, so it's one more place to remember to keep up to date, not convenient

**Comment by mrtraser** [comment]
I would add landing as a Readme file to give a brief library explanation to users. And I also agree that this one more thing that we need to keep updated manually.

**Comment by nalaka** [comment]
> frankly, I don't see the need of having so many pages. landing one - maybe, but it copies some info from npm anyway. Also there are a lot of WIP, so it's rather a draft. + the data in the table is static, so it's one more place to remember to keep up to date, not convenient

The NPM stats are not static- the values update automatically. For example, I "un starred" this repo on Github, and when I refresh the about page the star count was reduced by 1. It takes a few minutes for those services to update, but it is automatic - not copy pasted from npmjs.com and github.com at all 
:)

The pages other than "about" are drafts, I just wanted to illustrate the structure of what I think could be a great way to present Gearbox to users. The idea is to follow the [DITA](https://en.wikipedia.org/wiki/Darwin_Information_Typing_Architecture) guidelines to organize the information, where:

- DITA **Concepts** are in the DOCS section. This PR is regarding that, plus the storybook config is updated to custom order the entries in the sidebar.
- **Tasks** are in the EXAMPLES section. I have some preliminary work that I can put on a PR - an `AppProvider` component that can be used as a decorator for the stories which handles sign-in to a CDF tenant plus one or two examples.
- **References** are in the COMPONENTS section. This is the entirety of what we have now (before this PR). Also, I think these entries should be ordered alphabetically.

The component table on the about page is an index of all the 21 components Gearbox offers- Name and it's role/purpose. When we have all our components (tagged with their purpose) available at a glance, it is easier to think of the whole thing holistically, and see what is missing and what is not really useful. This could be very useful to our next step- i.e. thinking of Gearbox as a product rather than a solution and being more proactive. I discussed this with @hhenriques & @mrtraser at yesterday's stand-up- I suppose I did not articulate it this clearly though.  :)

Also, I was thinking maybe, instead of the logo at top, we can have an image that is a collage of our most prominent Gearbox components. I remember @f1cognite saying something on these lines sometime back.

If this is alright, let's merge this PR and PR #586 by @amevck which fixes the issue I mentioned in the first comment regarding the new about page not opening by default in Storybook. @polomani - since the merge request is only against the addon-docs branch (not release or master), maybe we can merge this now and iron out the details later in another PR?

**Comment by polomani** [comment]
> The NPM stats are not static- the values update automatically.
I was saying about "alphabetical list of components", not the stats

@nalaka at this moment pr requires a lot of ironing and blocks us from merging addon/docs, so I suggest to come back to this later. We could do it properly, defining the task first

**Comment by nalaka** [comment]
@polomani & @hhenriques - shall I remove all the WIP pages and leave just the landing page?

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-578.gearboxjs.preview.cogniteapp.com

**Comment by nalaka** [comment]
All WIP parts removed.

Replaced the logo with below collage of Gearbox components.

Screenshot 2020-01-12 at 18 25 10

Replaced the table of components with below high level overview of Gearbox.

> START QUOTE ----------

It is entirely possible to build the service layer of your **Cognite Data Fusion** powered web app by making direct HTTP calls to the **Cognite API** endpoints. But you don't have to: because, instead of HTTP calls, you can call the typed methods on the **CogniteClient** class from the **JavaScript SDK**.

Similarly, it is entirely possible to build the view layer from scratch. But you don't have to, because Gearbox gives you a set of **ReactJS** components to handle the most common use cases.

For example, to view all info on an asset given its ID, you just: `<AssetMeta assetId={420042000042042} />`.

Doing an `<AssetTree />` gives you a hierarchical view of all your assets. Now if you also take the `AssetSearch` component out of the gearbox, what you have are the basic building blocks of your app's navigation user experience.

`Model3DViewer` component lets you build user interfaces around navigating a 3D model of your assets, while the `TimeseriesChart` allows visualizing and interacting with the timeseries data streaming out of your assets.

There are many more components in Cognite Gearbox for you to pick and choose from. Continue reading to find out all about them.

> END QUOTE ----------

**Comment by nalaka** [comment]
Closing in favour of #603

**Pull request closed without merging**
