### PR TITLE
docs(time-series): improve mocked data (#569)

### PR DESCRIPTION
**Pull request by amevck**

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-577.gearboxjs.preview.cogniteapp.com

**Comment by amevck** [comment]
> It's not something that we really need. What we're trying to achieve here is the ability to configure timeseries view to render more distinctive plots. Best way to think about it is something like:
> 
> ```ts
> interface ConfigProps {
>   datapointsNumber: number;
>   minValue: number;
>   maxValue: number;
>   peaksNumber?: number;
>   positivePeakDeviation?: number;
>   negativePeakDeviation?: number; 
> }
> 
> const generateDataForChart = (config: ConfigProps) => {
>   // ...
> }
> ```
> 
> This function should produce the next kind of chart:
> Screenshot 2020-01-15 at 15 50 15
> 
> The main idea is to achieve visible distinctions between plots
>
If there are multiple series, Chart is automatically getting averages and realigned. for getting this king of Visualization we have to provide a custom y-domain (#551 ).

**Comment by amevck** [comment]
> I disagree, you'll have such kind of visualization also if your plot has one or more peaks on it (like in the picture above)

OK, I'll check with some peak points.

**Comment by polomani** [comment]
Not sure what you tried to achieve here @amevck , but yeah, the main point is to make plots more distinctive. Peaks suggestion could be a solutions, yes, but maybe something less advanced is also fine

**Comment by mrtraser** [comment]
Closed in favor #606

**Pull request closed without merging**
