### PR TITLE
refactor: remove console.warn from dataLoader

### PR DESCRIPTION
**Pull request by mrtraser**

### CODE REVIEW

**Comment by mrtraser** [comment]
Fixes #479

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-514.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-514.gearboxjs.preview.cogniteapp.com

**Pull request merged**
