### PR TITLE
chore: change approach to pass package version as variable

### PR DESCRIPTION
**Pull request by mrtraser**

### CODE REVIEW

**Comment by mrtraser** [comment]
Fixes #527

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-530.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-530.gearboxjs.preview.cogniteapp.com

**Pull request merged**
