### PR TITLE
Move antd to dependencies 

### LINKED ISSUE #639: antd@3 as peerDependency is preventing me from upgrading antd in my project
I can't upgrade to `antd@4` in my project because gearbox does not install it's own `v3` and is incompatible with `v4`

Suggested fixes:
1. Move `antd@^3.14.1` from `peedDependencies` to `dependencies`
2. Upgrade the entire project to be both `v3` and  `v4` compatible and change the peerDependency to something like `antd@>=3`.

### PR DESCRIPTION
**Pull request by vegardok**
Resolves #639

### CODE REVIEW

**Comment by polomani** [comment]
would it be an option to use an alias in your project?
https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-alias
```
yarn add antd4@npm:antd@4
```
and use it by
```
import { Button, DatePicker } from 'antd4';
```
?

**Comment by vegardok** [comment]
> would it be an option to use an alias in your project?

So I would have both and3 and ant4 in my dependencies, one to satisfy the peer dependency of gearbox and one that I actually use? That doesn't smell right to me. If this truly is a peer dependency you should maintain a version of gearbox for each major version of ant. But I'm not sure it is a peer dependency, I think it's an actual dependency.

**Comment by evancharlton** [comment]
I agree with https://github.com/cognitedata/gearbox.js/pull/669#issuecomment-662452121. This is an actual version-specific dependency (since it's relying on specific antd APIs).

I believe that @vegardok proposed the only two options that I see:
 - Cognite maintains versions of `@cognite/gearbox`
 - Apps ship two versions of antd (and have to somehow handle differences in styling, for example)

Of course, there's a third option, too:
 - Cognite bumps gearbox to antd@4 and says that the antd@3 version is no longer maintained.

Is there another option I'm overlooking? (Yikes, what an unfortunate situation, but such is life when we start using external dependencies)

**Comment by vegardok** [comment]
I thought a bit more about this, both moving ant to dependencies and having apps enforce two ant installation will result in the same and both will be problematic. If ant was a normal JS library the both should work and I would prefer the first option because libraries should not impose on app setups if it is avoidable. The downside would be multiple copies of different library versions in the bundle, but that is not a _big_ problem IMO. Data studio contains 3-4 `immutable.js` versions, not ideal, but it's not breaking anything. 

But since ant 3 and 4 expects a global CSS to be set up and added to the DOM then who knows what will happen with multiple versions. It doesn't sound like a good idea, we already have issues with multiple v3 ant css files added in fusion.

I think the best solution would be to replace ant with a different library that is more suitable as a library dependency. Possibly adding whatever is missing to cogs, but cogs have similar limitations as ant.

**Comment by evancharlton** [comment]
Agreed, @vegardok. I think that's why we realistically only have options 1 & 3 available to us:
 - Cognite maintains multiple versions of `@cognite/gearbox`
 - Cognite bumps gearbox to antd@4 and says that the antd@3 version is no longer maintained.

**Comment by danlevings** [comment]
Very interesting, thanks for the input!
The additional benefit is that we have quite a lot more control over cogs than antd, leading to more elegant solutions. We've discussed already the thought exporting 2 css files, one global for standard cases and one that wraps the entire sheet with `.cogs-v1` for example.
The more contributors to get cogs up and running the better, we have a good start of a components list but theres certainly more we need to do before we can move away from antd.

**Comment by polomani** [comment]
Thanks for the inputs. We'll need to wait a little bit because of people's vacation and then sort it out.
fyi @BugGambit @hhenriques @mrtraser

**Pull request closed without merging**
