### PR TITLE
Added new component ThreeDNodeTree

### PR DESCRIPTION
**Pull request by sharonsun1999**
Created a new component that visualizes the parent-child relationship of 3D nodes in a tree structure. It behaves the same with an asset tree except that the assets are replaced by 3D nodes of a model.

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-380.gearboxjs.preview.cogniteapp.com

**Comment by anderscognite** [comment]
@sharonsun1999 great work! Can you add some more description in this PR? (You can edit it above). Currently it's hard to know what this actually is. 

Also @f1cognite @mrtraser some tests are failing (not tests added in this PR), can you help us out?

**Comment by anderscognite** [comment]
The name of this component should maybe have a name indicating it is for 3D nodes.

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-380.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-380.gearboxjs.preview.cogniteapp.com

**Pull request merged**
