### PR TITLE
Don't highlight nodes on mount if cached

### PR DESCRIPTION
**Pull request by anderscognite**

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-305.gearboxjs.preview.cogniteapp.com

**Comment by anderscognite** [comment]
Some background: if everything is cached, then the camera and selections from last time are still intact. Now I have seen som unexpected behaviour.

**Comment by anderscognite** [comment]
Can we (as in you :D) release new version with this now?

**Comment by mrtraser** [comment]
> Some background: if everything is cached, then the camera and selections from last time are still intact. Now I have seen som unexpected behaviour.

Which unexpected behavior have you seen?

**Comment by andeplane** [comment]
I often handle selection outside the component (I may have my own methods of selecting things apart from assetId). If the component is mounted again, my selections are gone and the camera moves out to fit the model.

**Comment by anderscognite** [comment]
Damn, wrong account :P If we use `assetId` I think it also bounces out on remount (which is a bug).

**Comment by mrtraser** [comment]
I guess this PR should fix it, isn't it?

**Comment by anderscognite** [comment]
I think so :) Just wanted to add some context other than the title.

**Pull request merged**
