### PR TITLE
fix(tenant selector): add submitting on enter for all fields

### LINKED ISSUE #460: TenantSelector only submits on enter when project field is focused
When the project name field is focused, I can press enter to submit the form, but this behavior is missing from the "CDF Environment" field.

bilde

### PR DESCRIPTION
**Pull request by mrtraser**
* fixes #460

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-467.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
@valerii-cognite @evancharlton do you have any e2e tests that could break because of this change?
and any similar one (to know for the next time)

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-467.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-467.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-467.gearboxjs.preview.cogniteapp.com

**Pull request merged**
