### PR TITLE
Add cancelable promises to avoid isMounted() antipattern

### PR DESCRIPTION
**Pull request by mrtraser**

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-191.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
@xitman78 Something for you since you worked with it :)

**Comment by xitman78** [comment]
@f1cognite in my humble opinion, it still doesn't look like an elegant solution.

**Comment by mrtraser** [comment]
Solution will be replaced with example from https://github.com/cognitedata/gearbox.js/commit/b5a1028148b9ecdf58487ba34d4cd7ae78b819cd

**Pull request closed without merging**
