### PR TITLE
fix: sanitize SVGs with PNG

### PR DESCRIPTION
**Pull request by KatyHouse**

### CODE REVIEW

**Comment by polomani** [comment]
Hi @KatyHouse , could you explain what's going on a bit?

**Comment by KatyHouse** [comment]
@polomani So, some of our SVGs contains PNG image in ns1:href attribute and sanitize somehow deleted everything and showed a blanc picture, I asked @alexbrasetvik to help and this is a temporary solution he came up with :)

**Review by polomani — APPROVED** [review]
@KatyHouse ok, got you!

**Comment by valgussev** [comment]
omg

**Comment by polomani** [comment]
@valgussev too bad?)

**Comment by KatyHouse** [comment]
@valgussev No I don't think I asked, it's just the only pattern we faced

**Pull request merged**
