### PR TITLE
Fix Model3DViewer options behavior (assetId and enableKeyboardNavigation)

### LINKED ISSUE #368: Seems assetId prop on Model3DViewer doesnt work
I am loading a 3D model and setting the prop `assetId` on the `Model3DViewer` component but don't see that asset highlighted in the viewer.

### LINKED ISSUE #372: Model3DViewer - enableKeyboardNavigation is ignored when it is set to false
When setting `enableKeyboardNavigation` to false in `Model3DViewer` the keyboard still affects the camera position in the viewer.
I think the problem here is that the 3d-viewer have keyboard-navigation is enabled by default and we never turn it off.

### PR DESCRIPTION
**Pull request by mrtraser**
Fixes #368 
Fixes #372

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-374.gearboxjs.preview.cogniteapp.com

**Comment by andeplane** [comment]
Won't this force a new animation if the component is unmounted, then mounted again? In my eyes, if you have selected an asset, it makes sense that it animates there. If you go away from the 3D viewer and back in again, focusing on the same `assetId`, I don't expect another animation.

**Comment by anderscognite** [comment]
Won't this force a new animation if the component is unmounted, then mounted again? In my eyes, if you have selected an asset, it makes sense that it animates there. If you go away from the 3D viewer and back in again, focusing on the same assetId, I don't expect another animation.

**Comment by mrtraser** [comment]
@anderscognite, so your point is to have animation only when viewer have `assetId` prop during first init (when viewer instance doesn't come from a cached object), am I right?

**Comment by anderscognite** [comment]
Yes, if the user moved the camera it is weird if it gets reset :)

**Comment by mrtraser** [comment]
@anderscognite, fixed in the last commit to fit your description.

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-374.gearboxjs.preview.cogniteapp.com

**Comment by anderscognite** [comment]
Lgtm!

**Pull request merged**
