### PR TITLE
fix: add guard/default to avoid accessing undefined [OI-2736]

### PR DESCRIPTION
**Pull request by eiriklv**
[OI-2736](https://cognitedata.atlassian.net/browse/OI-2736)

There aren't always data points, which causes a crash:

Skjermbilde 2020-11-02 kl  14 18 17

### CODE REVIEW

**Comment by eiriklv** [comment]
There might be a better way to default this than `0`

**Comment by polomani** [comment]
zero is not going to work properly in here, I'd suggest to `arr.filter(({ datapoints }) => datapoints.lenght).map(({ datapoints: [item] }) => item.timestamp.getTime()`

**Comment by eiriklv** [comment]
> zero is not going to work properly in here, I'd suggest to `arr.filter(({ datapoints }) => datapoints.length).map(({ datapoints: [item] }) => item.timestamp.getTime()`

Great - will make the change. Thanks!

**Comment by eiriklv** [comment]
Anyone know why "Preview Deployment" doesn't work?

**Comment by eiriklv** [comment]
@polomani Who could I ask about the build process issue?

**Comment by polomani** [comment]
@eiriklv I believe you have to open a PR from the same repo, so you might need to get an access from @hhenriques

**Comment by eiriklv** [comment]
Made a PR from this repo, so I'm closing this

**Pull request closed without merging**
