### PR TITLE
feat(timeseries-data-export): form selection props

### PR DESCRIPTION
**Pull request by hernil**
New prop that allows to pass in optional default selections for some of the export dialog form fields.

### CODE REVIEW

**Comment by hernil** [comment]
Upgrading prettier seems to have some changes in opinions. Any preference on how I should procede fixing these @polomani? 😄

**Comment by polomani** [comment]
have you tried `yarn lint --fix`?

**Comment by hernil** [comment]
> 
> 
> have you tried `yarn lint:fix`?

I have, and that changes files unrelated to my changes. Should I just tuck them into the upgrade commit?

**Comment by polomani** [comment]
nah, that sounds like a separate PR. could you not use the optional chaining thing?

**Review by polomani — APPROVED** [review]

**Pull request merged**
