### PR TITLE
docs(readme): intro guide for docs.cognite.com

### PR DESCRIPTION
**Pull request by polomani**
applies changes from this PR https://github.com/cognitedata/doc.cognitedata.com/pull/199
we want to keep the guide sources in only one place use it in multiple

### CODE REVIEW

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-425.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-425.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-425.gearboxjs.preview.cogniteapp.com

**Comment by f1cognite** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-425.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
@f1cognite fixed that

**Pull request merged**
