### PR TITLE
docs(asset-scanner): rewrite stories in new format

### PR DESCRIPTION
**Pull request by amevck**

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-548.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
why is this a draft?

**Comment by mrtraser** [comment]
You forgot to add decorator for client SDK mock, that's why `Custom ocrRequest` shows wrong results

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-548.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-548.gearboxjs.preview.cogniteapp.com

**Pull request merged**
