### PR TITLE
Added possibility to add children to Model3DViewer

### LINKED ISSUE #499: Can't render children in Model3DViewer
In my application, I want to add HTML objects on top of the 3D viewer canvas. I want these objects to handle click events, but not mouse move or wheel events (because that usually is interaction with 3d viewer). In order to do this properly, I need to render my HTML objects as children inside the `Model3DViewer` component so that events first reach my html objects, so I can propage the ones I'm not interested in further to the canvas.

Today, this is not possible as nothing is rendered if it is a child inside `<Model3DViewer><... /></Model3DViewer>`.

### PR DESCRIPTION
**Pull request by andeplane**
Closes #499

### CODE REVIEW

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-506.gearboxjs.preview.cogniteapp.com

**Comment by polomani** [comment]
@anderscognite click events work the way you expected?

**Comment by anderscognite** [comment]
I never got to test fully in my app, but it seems pretty good!

**Comment by andeplane** [comment]
Mixing up the GH accounts here. So I just tested with `antd` icons, but never got to the point where I was able to pass through the mouse move events. Let's keep this PR open until I have proved that it works :)

**Comment by polomani** [comment]
@andeplane if you have a test for it would be awesome as well :)

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-506.gearboxjs.preview.cogniteapp.com

**Comment by mrtraser** [comment]
Closes #498

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-506.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-506.gearboxjs.preview.cogniteapp.com

**Comment by cognite-cicd** [comment]
This PR's storybook can now be previewed at the following URL: https://pr-506.gearboxjs.preview.cogniteapp.com

**Pull request merged**
